server:
  port: 8085

spring:
  application:
    name: session-service

redis:
    host: localhost
    port: 6379

jwt:
  secret: hKfYbV1L1LwzFX2Yw8hEHyTj3E4xjV5SyJ6eR3Jg+oE=

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs