server:
  port: 8085

spring:
  application:
    name: session-service

redis:
    host: localhost
    port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs